# Generated by Django 4.1.5 on 2023-05-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all', '0003_color_size_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('out of order', 'out of order'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('in progress', 'in progress')], max_length=200, null=True)),
                ('Color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.color')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.product')),
                ('Size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.size')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
