# Generated by Django 4.1.5 on 2023-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out of order', 'out of order'), ('Delivered', 'Delivered'), ('in progress', 'in progress'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
